services:
  staging_web:
    image: nginx:stable-alpine
    container_name: staging_web
    volumes:
      - ../../dist:/usr/share/nginx/html:ro
      - ../../nginx-spa.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    external: true